version: '3'

services:
  mongo:
      volumes:
          - './mongo_data:/data/db'
      ports:
          - '27017:27017'
      image: mongo
      container_name: mongo
  nodejs:
    build:
      context: .
      dockerfile: Dockerfile
    image: nodejs
    container_name: nodejs
    restart: unless-stopped
    env_file: .env
    volumes:
      - ./:/usr/src/app
      - node_modules:/home/node/app/node_modules
